version: "2.4"
services:
  rabbitmq:
    image: docker.iranserver.com/bitnami/rabbitmq
    container_name: rabbitmq_iot
    restart: always
    ports:
      - "15672:15672" 
      - "5672:5672"   
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypass
    networks:
      - iot-network
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:7.0
    container_name: mongo_iot
    ports:
      - "27017:27017"
    networks:
      - iot-network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5

  agent:
    build:
      context: ../../agent
      dockerfile: Dockerfile
    container_name: agent_iot
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - iot-network

  process:
    build:
      context: ../../process
      dockerfile: Dockerfile
    container_name: process_iot
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - iot-network

volumes:
  mongo_data:

networks:
  iot-network:
    driver: bridge
